-- MySQL Script generated by MySQL Workbench
-- Tue Aug 23 18:40:01 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema bug_tracker_db
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema bug_tracker_db
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `bug_tracker_db` DEFAULT CHARACTER SET utf8 ;
USE `bug_tracker_db` ;

-- -----------------------------------------------------
-- Table `bug_tracker_db`.`account`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bug_tracker_db`.`account` (
  `idaccount` TINYINT NOT NULL AUTO_INCREMENT,
  `email` VARCHAR(255) NOT NULL,
  `password` VARCHAR(128) NOT NULL,
  `created` DATETIME NOT NULL,
  `isActive` CHAR(2) NOT NULL DEFAULT 0,
  PRIMARY KEY (`idaccount`),
  UNIQUE INDEX `email_UNIQUE` (`email` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bug_tracker_db`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bug_tracker_db`.`user` (
  `iduser` TINYINT NOT NULL AUTO_INCREMENT,
  `firstname` VARCHAR(45) NOT NULL,
  `lastname` VARCHAR(45) NOT NULL,
  `empid` BIGINT(15) NOT NULL,
  `joinDate` DATETIME NOT NULL,
  `leaveDate` DATETIME NULL,
  `accountRef` TINYINT NULL,
  PRIMARY KEY (`iduser`),
  UNIQUE INDEX `empid_UNIQUE` (`empid` ASC) VISIBLE,
  INDEX `user_acc_FK_idx` (`accountRef` ASC) VISIBLE,
  CONSTRAINT `user_acc_FK`
    FOREIGN KEY (`accountRef`)
    REFERENCES `bug_tracker_db`.`account` (`idaccount`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bug_tracker_db`.`designation`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bug_tracker_db`.`designation` (
  `iddesignation` TINYINT NOT NULL,
  `designationTitle` VARCHAR(25) NOT NULL,
  PRIMARY KEY (`iddesignation`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bug_tracker_db`.`team`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bug_tracker_db`.`team` (
  `idteam` TINYINT NOT NULL AUTO_INCREMENT,
  `teamTitle` VARCHAR(25) NOT NULL,
  PRIMARY KEY (`idteam`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bug_tracker_db`.`permission`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bug_tracker_db`.`permission` (
  `idpermission` TINYINT NOT NULL AUTO_INCREMENT,
  `permissionTitle` CHAR(10) NOT NULL,
  PRIMARY KEY (`idpermission`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bug_tracker_db`.`employeeInfo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bug_tracker_db`.`employeeInfo` (
  `empId` BIGINT(15) NOT NULL,
  `accountRef` TINYINT NULL,
  `designationRef` TINYINT NULL,
  `teamRef` TINYINT NULL,
  `permissionRef` TINYINT NULL,
  PRIMARY KEY (`empId`),
  UNIQUE INDEX `empId_UNIQUE` (`empId` ASC) VISIBLE,
  INDEX `empInfo_acc_FK_idx` (`accountRef` ASC) VISIBLE,
  INDEX `empInfo_des_FK_idx` (`designationRef` ASC) VISIBLE,
  INDEX `empInfo_team_FK_idx` (`teamRef` ASC) VISIBLE,
  INDEX `empInfo_perm_FK_idx` (`permissionRef` ASC) VISIBLE,
  CONSTRAINT `empInfo_acc_FK`
    FOREIGN KEY (`accountRef`)
    REFERENCES `bug_tracker_db`.`account` (`idaccount`)
    ON DELETE SET NULL
    ON UPDATE CASCADE,
  CONSTRAINT `empInfo_des_FK`
    FOREIGN KEY (`designationRef`)
    REFERENCES `bug_tracker_db`.`designation` (`iddesignation`)
    ON DELETE SET NULL
    ON UPDATE CASCADE,
  CONSTRAINT `empInfo_team_FK`
    FOREIGN KEY (`teamRef`)
    REFERENCES `bug_tracker_db`.`team` (`idteam`)
    ON DELETE SET NULL
    ON UPDATE CASCADE,
  CONSTRAINT `empInfo_perm_FK`
    FOREIGN KEY (`permissionRef`)
    REFERENCES `bug_tracker_db`.`permission` (`idpermission`)
    ON DELETE SET NULL
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bug_tracker_db`.`category`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bug_tracker_db`.`category` (
  `idcategory` TINYINT NOT NULL AUTO_INCREMENT,
  `categoryTitle` VARCHAR(15) NOT NULL,
  PRIMARY KEY (`idcategory`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bug_tracker_db`.`priority`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bug_tracker_db`.`priority` (
  `idpriority` TINYINT NOT NULL AUTO_INCREMENT,
  `priorityTitle` VARCHAR(15) NOT NULL,
  PRIMARY KEY (`idpriority`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bug_tracker_db`.`ticketStatus`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bug_tracker_db`.`ticketStatus` (
  `idticketStatus` TINYINT NOT NULL,
  `statusTitle` VARCHAR(15) NOT NULL,
  PRIMARY KEY (`idticketStatus`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bug_tracker_db`.`ticket`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bug_tracker_db`.`ticket` (
  `idticket` INT NOT NULL AUTO_INCREMENT,
  `title` VARCHAR(25) NOT NULL,
  `description` VARCHAR(350) NOT NULL,
  `statusRef` TINYINT NULL,
  `priorityRef` TINYINT NULL,
  `categoryRef` TINYINT NULL,
  `empRef` BIGINT(15) NOT NULL,
  PRIMARY KEY (`idticket`),
  INDEX `ticket_cat_FK_idx` (`categoryRef` ASC) VISIBLE,
  INDEX `ticket_prio_FK_idx` (`priorityRef` ASC) VISIBLE,
  INDEX `ticket_stat_FK_idx` (`statusRef` ASC) VISIBLE,
  INDEX `empRef_idx` (`empRef` ASC) VISIBLE,
  CONSTRAINT `ticket_cat_FK`
    FOREIGN KEY (`categoryRef`)
    REFERENCES `bug_tracker_db`.`category` (`idcategory`)
    ON DELETE SET NULL
    ON UPDATE CASCADE,
  CONSTRAINT `ticket_prio_FK`
    FOREIGN KEY (`priorityRef`)
    REFERENCES `bug_tracker_db`.`priority` (`idpriority`)
    ON DELETE SET NULL
    ON UPDATE CASCADE,
  CONSTRAINT `ticket_stat_FK`
    FOREIGN KEY (`statusRef`)
    REFERENCES `bug_tracker_db`.`ticketStatus` (`idticketStatus`)
    ON DELETE SET NULL
    ON UPDATE CASCADE,
  CONSTRAINT `empRef`
    FOREIGN KEY (`empRef`)
    REFERENCES `bug_tracker_db`.`employeeInfo` (`empId`)
    ON DELETE NO ACTION
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bug_tracker_db`.`ticketEmployee`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bug_tracker_db`.`ticketEmployee` (
  `ticketRef` INT NOT NULL,
  `empRef` BIGINT(15) NULL,
  `comment` VARCHAR(350) NULL,
  INDEX `tEmp_empInfo_FK_idx` (`empRef` ASC) VISIBLE,
  PRIMARY KEY (`ticketRef`),
  CONSTRAINT `tEmp_ticket_FK`
    FOREIGN KEY (`ticketRef`)
    REFERENCES `bug_tracker_db`.`ticket` (`idticket`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `tEmp_empInfo_FK`
    FOREIGN KEY (`empRef`)
    REFERENCES `bug_tracker_db`.`employeeInfo` (`empId`)
    ON DELETE SET NULL
    ON UPDATE CASCADE)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
